"""add_auth_fields

Revision ID: a3e10e1e5635
Revises: b4623f8f4339
Create Date: 2026-03-19 15:33:27.967592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e10e1e5635'
down_revision: Union[str, Sequence[str], None] = 'b4623f8f4339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('invite_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.drop_column('users', 'invite_token_expires_at')
    op.drop_column('users', 'invite_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
