"""add sprite preview columns to media_files (merge 3 heads)

Adds two nullable text columns to ``media_files`` for the timeline-hover
preview feature (Frame.io-style instant scrubbing):

  s3_key_sprite       — JPG sprite sheet (10x10 tile grid).
  s3_key_sprite_vtt   — WebVTT track mapping each timestamp range to a
                        tile via ``#xywh=`` media fragments.

Both nullable: existing media_files rows continue to work via the
legacy live-seek hidden-video preview. Once a sprite is generated by
the worker, the player switches automatically to the cached sprite.

This revision is also a 3-way merge of the previous alembic heads:
  4094df400c86 (add_visibility_to_comments)
  f5c6d7e8f9a0 (add_api_tokens)
  a11ce9b821a0 (add_pending_verification_to_userstatus)

Revision ID: c2e8f1a3b5d7
Revises: 4094df400c86, f5c6d7e8f9a0, a11ce9b821a0
Create Date: 2026-05-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c2e8f1a3b5d7"
down_revision: Union[str, Sequence[str], None] = (
    "4094df400c86",
    "f5c6d7e8f9a0",
    "a11ce9b821a0",
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "media_files",
        sa.Column("s3_key_sprite", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "media_files",
        sa.Column("s3_key_sprite_vtt", sa.String(length=1000), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("media_files", "s3_key_sprite_vtt")
    op.drop_column("media_files", "s3_key_sprite")
